//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishScale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fishscale
    {
        public int clienteid { get; set; }
        public string nome { get; set; }
        public Nullable<int> maquinaid { get; set; }
        public string sistemaoperacional { get; set; }
        public Nullable<double> freehd { get; set; }
        public Nullable<double> usedhd { get; set; }
        public Nullable<double> freeram { get; set; }
        public Nullable<double> usedram { get; set; }
        public Nullable<System.DateTime> dataview { get; set; }
    }
}
