//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishScale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitoracao
    {
        public int MonitoraID { get; set; }
        public Nullable<double> TotalRAM { get; set; }
        public Nullable<double> TotalHD { get; set; }
        public Nullable<double> UsedRAM { get; set; }
        public Nullable<double> UsedHD { get; set; }
        public string HoraMonitoracao { get; set; }
        public Nullable<int> MaquinaID { get; set; }
        public Nullable<int> ClienteID { get; set; }
    }
}
